# Site Settings
title: My Resume
description: A beautiful Jekyll theme for creating a resume
url: 'http://webjeda.com'  # Update to your site's URL

# Style options
theme: minima  # Specify your theme here, or use 'minima' as a default
theme_skin: blue
chrome_mobile_color: 

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Collections Settings for Pages
# You don't need to configure a custom collection if using default posts
collections:
  posts:
    output: true  # This is true by default for posts, but you can specify it explicitly

# Include directories
include:
  - _pages  # Include any additional directories if needed

# Exclude directories (optional, specify if there are directories you don't want to process)
exclude:
  - node_modules
  - vendor/bundle
  - Gemfile
  - Gemfile.lock

# Permalink Settings
permalink: /:categories/:year/:month/:day/:title/  # You can adjust this if you want a different URL structure

# Defaults
defaults:
  - scope:
      path: ""  # Empty path means this applies to all files
      type: "posts"
    values:
      layout: "post"  # Make sure your post layout is named 'post.html' in the _layouts directory
  - scope:
      path: ""  # This applies to all pages
      type: "pages"
    values:
      layout: "default"

# Plugins (add any plugins you are using here)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown Processor
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# Optional settings
encoding: "utf-8"
