# Site Settings
title: My Resume
url: 'http://webjeda.com'

# Uncomment or modify the baseurl setting if needed
# baseurl: '/your-repo-name' # Use this if your site is hosted in a subdirectory (GitHub Pages)

description: A beautiful Jekyll theme for creating resumes
theme_skin: blue # Options: blue, turquoise, green, berry, orange, ceramic, teal, oceanstale
chrome_mobile_color: "#1976d2" # Hex color for Chrome mobile search bar

# Tracker
analytics: UA-83979019-1

# Sass/SCSS Settings
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression Settings
compress-site: true

# Jekyll HTML Compression Plugin
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Collections Settings for Pages
collections:
  pages:
    output: true

# Permalink Settings
# Define the default permalink structure for all pages
permalink: pretty

# Include `_pages` directory in the collection
include:
  - _pages

# Any additional settings for Jekyll can go here
encoding: "utf-8"
